### ISSUE TITLE
One Expanded card at time 

### ISSUE THREAD

**Issue by everancii** [datdescartes/expansion_widget#1]
Hello, first of all its a really great library , i love it. And i faced a common problem with expanding one tile at time. I tried alot of different solutions but nothing works for me, only if i put key: GlobalKey(), thats work but animation stops working. Thanks in advance

**Comment by datvu7** [comment]
@everancii  Could you give me some simple code? So, I can figure out the problem.

**Comment by datvu7** [comment]
@everancii I have just released v0.0.2 that exposes the state. Now, you can use globalKey.currentState?.expand (or collapse/toggle) to expand the widget.

Hope this can help you solve the problem!

https://github.com/datdescartes/expansion_widget/blob/3609bfbb0cb02182fb469c682dc1ec67e209b966/example/lib/main.dart#L162

**Comment by everancii** [comment]
That's great. Its work fabulously. Thanks alot :)
